package model.entity;
// Generated 08-jul-2012 20:26:27 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cabecera generated by hbm2java
 */
public class Cabecera  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Proveedor proveedor;
     private Date fecha;
     private Character operacion;
     private Integer serie;
     private Integer numero;
     private BigDecimal subtotal;
     private BigDecimal ivg;
     private BigDecimal total;
     private Set<Detalle> detalles = new HashSet<Detalle>(0);

    public Cabecera() {
    }

    public Cabecera(Cliente cliente, Proveedor proveedor, Date fecha, Character operacion, Integer serie, Integer numero, BigDecimal subtotal, BigDecimal ivg, BigDecimal total, Set<Detalle> detalles) {
       this.cliente = cliente;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.operacion = operacion;
       this.serie = serie;
       this.numero = numero;
       this.subtotal = subtotal;
       this.ivg = ivg;
       this.total = total;
       this.detalles = detalles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Character getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(Character operacion) {
        this.operacion = operacion;
    }
    public Integer getSerie() {
        return this.serie;
    }
    
    public void setSerie(Integer serie) {
        this.serie = serie;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public BigDecimal getIvg() {
        return this.ivg;
    }
    
    public void setIvg(BigDecimal ivg) {
        this.ivg = ivg;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set<Detalle> getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set<Detalle> detalles) {
        this.detalles = detalles;
    }




}


