package model.entity;
// Generated 08-jul-2012 20:26:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private String dniruc;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private Set<Cabecera> cabeceras = new HashSet<Cabecera>(0);

    public Cliente() {
    }

	
    public Cliente(String dniruc) {
        this.dniruc = dniruc;
    }
    public Cliente(String dniruc, String nombres, String apellidos, String direccion, String telefono, String celular, String email, Set<Cabecera> cabeceras) {
       this.dniruc = dniruc;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.cabeceras = cabeceras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDniruc() {
        return this.dniruc;
    }
    
    public void setDniruc(String dniruc) {
        this.dniruc = dniruc;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Cabecera> getCabeceras() {
        return this.cabeceras;
    }
    
    public void setCabeceras(Set<Cabecera> cabeceras) {
        this.cabeceras = cabeceras;
    }




}


