package model.entity;
// Generated 08-jul-2012 20:26:27 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private Integer id;
     private Cabecera cabecera;
     private Producto producto;
     private BigDecimal precio;
     private BigDecimal cantidad;

    public Detalle() {
    }

    public Detalle(Cabecera cabecera, Producto producto, BigDecimal precio, BigDecimal cantidad) {
       this.cabecera = cabecera;
       this.producto = producto;
       this.precio = precio;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cabecera getCabecera() {
        return this.cabecera;
    }
    
    public void setCabecera(Cabecera cabecera) {
        this.cabecera = cabecera;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


