package model.entity;
// Generated 08-jul-2012 20:26:27 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer id;
     private String ruc;
     private String razonSocial;
     private String nombreComercial;
     private String representante;
     private String cargo;
     private String direccion;
     private String telefono;
     private String celular;
     private String email;
     private Set<Cabecera> cabeceras = new HashSet<Cabecera>(0);

    public Proveedor() {
    }

	
    public Proveedor(String ruc, String razonSocial) {
        this.ruc = ruc;
        this.razonSocial = razonSocial;
    }
    public Proveedor(String ruc, String razonSocial, String nombreComercial, String representante, String cargo, String direccion, String telefono, String celular, String email, Set<Cabecera> cabeceras) {
       this.ruc = ruc;
       this.razonSocial = razonSocial;
       this.nombreComercial = nombreComercial;
       this.representante = representante;
       this.cargo = cargo;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.cabeceras = cabeceras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Cabecera> getCabeceras() {
        return this.cabeceras;
    }
    
    public void setCabeceras(Set<Cabecera> cabeceras) {
        this.cabeceras = cabeceras;
    }




}


